### ISSUE TITLE
Electron Sengi doesn't properly resize in i3wm on Linux

### ISSUE THREAD

**Issue by melissasage** [NicolasConstant/sengi#205]
I'm using the snap version, and I honestly didn't even know that Sengi was build with responsive sizing until looking at the readme on github, since i3wm defaults new windows to fullscreen. If you reduce the size of the window, you just get a smaller window with nothing resized, causing you to have to scroll.

given that this is kind of specific, I might try to figure this out on my own and report back here, but I wanted to open the issue to let you know.

**Comment by NicolasConstant** [comment]
Can you provide me some screenshots of the issue? 
I think I see what you're experiencing but I just want to be sure.

**Comment by melissasage** [comment]
here, with a terminal in the other window.
![DeepinScreenshot_select-area_20191220104832](https://user-images.githubusercontent.com/25471399/71266498-8a9cb580-2316-11ea-9468-447dd6a5647e.png)

**Comment by melissasage** [comment]
and with an arbitrary number of terminals, at a size that should definitely trigger resizing.
![DeepinScreenshot_select-area_20191220105135](https://user-images.githubusercontent.com/25471399/71266633-d0597e00-2316-11ea-8ec1-6d3689980747.png)

**Comment by NicolasConstant** [comment]
Thanks for those screens! 
I see the issue but I can't promise a fix in a close future: due to the stacking aspect of the columns, a CSS only solution won't be possible and would require a heavy part of JS logic. 
Unless I find a trick that won't require such work of course. :)

**Comment by yannicka** [comment]
I'm not sure it fixes this issue, but would flexible columns help (as a parameter, not a default value)?

![gif animation example](https://user-images.githubusercontent.com/22885898/82840316-5f744e80-9ed2-11ea-99a5-bd446c9f5177.gif)

The CSS used in the example (for testing purposes):

```css
.main-display {
    display: flex;
}

html body .main-display .main-display__stream-column {
    flex: 1;
    width: auto;
    min-width: 320px;
    max-width: 640px;
}

html body .main-display .stream-column {
    width: auto;
}

html body .main-display .sliding-column {
    width: auto;
}

html body .main-display .stream-statuses {
    width: auto;
}

html body .main-display .stream-column__stream-header {
    width: auto;
}

html body .main-display .stream-column__stream-selector {
    width: auto;
}

html body .main-display .stream-toots {
    overflow: hidden;
}
```
